---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
Rakefile:
  param_docs_pattern:
    - manifests/foreman_proxy_content.pp
    - manifests/init.pp
spec/spec_helper_acceptance.rb:
  install_epel: true
